name: Conditional Workflow

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Project
        run: echo "Building project for PR to ${GITHUB_REF} branch"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Tests
        run: echo "Running tests for PR to ${GITHUB_REF} branch"

  sonar:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: SonarQube Analysis
        run: echo "Running SonarQube analysis for master branch"

  fortify:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Fortify Security Scan
        run: echo "Running Fortify security scan for master branch"

  deploy:
    runs-on: ubuntu-latest
    # needs: |
    #   test
    #   fortify  # Only runs if fortify is executed (for master)
    steps:
      - name: Deploy Application
        run: echo "Deploying application for ${GITHUB_REF} branch"

  finish:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Finish Process
        run: echo "Finished workflow for ${GITHUB_REF} branch"
