name: Conditional Workflow

on:
  pull_request:
    branches:
      - dev
      - master

env:
  SHARED_VARIABLE: "This is a shared variable"

jobs:
  # Job for PR to the dev or master branch
  build:
    if: github.base_ref == 'dev' || (github.base_ref == 'master' && github.head_ref == 'dev')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Build Message
        run: echo "Building project for PR to ${GITHUB_BASE_REF} branch"

  test:
    if: github.base_ref == 'dev' || (github.base_ref == 'master' && github.head_ref == 'dev')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Echo Test Message
        run: echo "Running tests for PR to ${GITHUB_BASE_REF} branch"

  # Additional testing jobs only for PR to master from dev
  mutation-test:
    if: github.base_ref == 'master' && github.head_ref == 'dev'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Echo Mutation Test Message
        run: echo "Running mutation tests for PR to master branch from dev"

  regression-test:
    if: github.base_ref == 'master' && github.head_ref == 'dev'
    runs-on: ubuntu-latest
    needs: mutation-test
    steps:
      - name: Echo Regression Test Message
        run: echo "Running regression tests for PR to master branch from dev"

  business-test:
    if: github.base_ref == 'master' && github.head_ref == 'dev'
    runs-on: ubuntu-latest
    needs: regression-test
    steps:
      - name: Echo Business Test Message
        run: echo "Running business tests for PR to master branch from dev"

  security-test:
    if: github.base_ref == 'master' && github.head_ref == 'dev'
    runs-on: ubuntu-latest
    needs: business-test
    steps:
      - name: Echo Security Test Message
        run: echo "Running security tests for PR to master branch from dev"

  # Create Docker image
  docker-image:
    runs-on: ubuntu-latest
    needs: 
      - test
      - security-test  # Security test will only run for master PRs
    steps:
      - name: Echo Docker Image Creation Message
        run: echo "Creating Docker image for PR to ${GITHUB_BASE_REF} branch"

  # Shared deployment job for both dev and master branches
  deploy:
    runs-on: ubuntu-latest
    needs: docker-image
    steps:
      - name: Echo Deployment Message
        run: echo "Deploying to ${GITHUB_BASE_REF} environment"

  finish:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Finish Message
        run: echo "Finished processing PR to ${GITHUB_BASE_REF} branch"
