on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5
    needs: job1

  job3:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
    needs: job1

  job3-1:
      runs-on: ubuntu-latest
      steps:
        - run: sleep 10
      needs: job1
  
  job4:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - run: echo "job4"
    needs: [job2, job3]

  job5:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: echo "job4"
    needs: [job1, job3-1]